version: '2'

services:
  elasticsearch:
    image: jkris/elasticsearch:5
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    networks:
      - elk-curator-docker
  logstash:
    image: jkris/logstash:5
    command: -f /etc/logstash/conf.d/
    volumes:
      - ./logstash/config:/etc/logstash/conf.d
    ports:
      - "5000:5000"
    networks:
      - elk-curator-docker
  kibana:
    image: jkris/kibana:5
    volumes:
      - ./kibana/config/:/opt/kibana/config/
    ports:
      - "5601:5601"
    networks:
      - elk-curator-docker

networks:
  elk-curator-docker:
    driver: bridge
